main:
  - name: "About"
    identifier: "about"
    url: "/about/"
    weight: 10
    params:
      description: "Bio, education, experience, awards"
  - name: "Research"
    identifier: "research"
    url: "/research/"
    weight: 20
    params:
      description: "Biophysical and social drivers of change"
  - name: "Gallery"
    identifier: "gallery"
    url: "/gallery/"
    weight: 30
    params:
      description: "Anthologies, personal work"
  - name: "Outreach"
    identifier: "outreach"
    url: "/outreach/"
    weight: 40
    params:
      description: "Media, press, writing"
  - name: "Blog"
    identifier: "blog"
    url: "/blog/"
    weight: 50
    params:
      description: "Coding posts and notes"
  - name: "Contact"
    identifier: "contact"
    url: "/contact/"
    weight: 60
    params:
      description: "Get in touch"
