---
description: "Oceanic and Atmospheric Scientist, investigating the physical and social drivers of environmental change"
mainSections: ["blog"]
date_format: "2006-01-02"

header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "Robert J. Dellinger"
      filename: "logo.svg"
    show_theme_chooser: true
    show_search: true
    highlight_active_link: true
    show_translations: false
    hide_language_name: false

features:
  math:
    enable: true
  diagrams:
    enable: true
  repository:
    url: "https://github.com/robertjdellinger/robertjdellinger.github.io"
    content_dir: "content"
    branch: "main"

footer:
  block: minimal
  copyright:
    notice: "Â© {year} Robert J. Dellinger, This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  show_translations: false

assets:
  favicon: "media/icon.png"

seo:
  site_type: "Person"
  org_name: "UCLA Atmospheric and Oceanic Sciences"

privacy:
  youtube:
    privacyEnhanced: true
  x:
    enableDNT: true
---
