############################
## PARAMS
############################
description: "Oceanic and Atmospheric Scientist investigating the physical and social drivers of environmental change."
mainSections: ["blog"]
date_format: "2006-01-02"

params:
  author:
    name: "Robert J. Dellinger"
    affiliation: "UCLA Atmospheric and Oceanic Sciences"
    orcid: "0009-0009-3524-4041"
    orcid_url: "https://orcid.org/0009-0009-3524-4041"
    email: "rjdellinger@ucla.edu"         # publish only if intended
    telephone: "+13108809842"             # E.164 for tel: links
    jobTitle: "PhD Student"

  short_title: "Robert J. Dellinger"
  short_description: "Oceanic & Atmospheric Scientist"
  description_long: "Investigating how physical and social forces drive environmental change, translating science into policy and community action."
  show_reading_time: true

  social:
    twitter:
      url: "https://twitter.com/RJ_Dellinger"
    github:
      url: "https://github.com/robertjdellinger"
    linkedin:
      url: "https://www.linkedin.com/in/robertjdellinger"
    orcid:
      url: "https://orcid.org/0009-0009-3524-4041"

  default_image: "/assets/media/icons/logo.png"

assets:
  favicon: "/assets/media/icons/icon.png"
  logo:
    light: "/assets/media/icons/logo.png"
    dark: "/assets/media/icons/logo.png"
