############################
## TAXONOMIES & PARAMS
############################
taxonomies:
  tag: tags
  category: categories
  author: authors
  publication_type: publication_types
  series: series
